name: challenge__tracker
on:
  push:
    branches: ["main"]


# Author: Hinami.

jobs:
  challenge-tracker:
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          output: ","
          fileOutput: ","

      - id: github-checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: update counter
        run: |
          
          chmod +x "${GITHUB_WORKSPACE}/.github/scripts/shell.sh"       
            # run script
          "${GITHUB_WORKSPACE}/.github/scripts/shell.sh" "${{ steps.file_changes.outputs.files}}" "${GITHUB_WORKSPACE}"

