name: challenge__validator
on: [pull_request]
jobs:
  challenge-validator:
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          output: ","
          fileOutput: ","

      - id: github-checkout
        uses: actions/checkout@v2
      - name: Update counter
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: update counter
        run: |
          # scripts/shell.sh
          chmod +x "${GITHUB_WORKSPACE}/.github/scripts/shell.sh"       
            # run script
          "${GITHUB_WORKSPACE}/.github/scripts/shell.sh" "${{ steps.file_changes.outputs.files}}" "${GITHUB_WORKSPACE}"
          echo Updating ...
          git config --global user.name "minaiscoding"
          git config --global user.email "khadir04kh@gmail.com"
          git add counter.yaml
          git commit -m 'updated counter'
          git branch -a
          git push origin main
