name: challenge__validator
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  challenge-validator:
    runs-on: ubuntu-latest
    steps:

      - id: github-checkout
        uses: actions/checkout@v1

      - name: count
        run: |
          python ../scripts/python.py testing.yaml